<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.iseekfree.common</groupId>
        <artifactId>sdk-webmvc-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>sdk-bom</artifactId>
    <packaging>pom</packaging>
    <name>${project.artifactId}</name>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.iseekfree.common</groupId>
                <artifactId>sdk-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.iseekfree.common</groupId>
                <artifactId>sdk-mongo</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.iseekfree.common</groupId>
                <artifactId>sdk-redis</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.iseekfree.common</groupId>
                <artifactId>sdk-web</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.iseekfree.common</groupId>
                <artifactId>sdk-grpc-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.iseekfree.common</groupId>
                <artifactId>sdk-grpc-server</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.iseekfree.common</groupId>
                <artifactId>sdk-grpc-client</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.iseekfree.common</groupId>
                <artifactId>sdk-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
